[project]
name = "resume-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-genai>=1.0.0",
    "pymupdf>=1.26.7",
    "python-docx>=1.1.0",
    "python-dotenv>=1.1.0",
]
